services:
  api-idp:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file:
      - .env
    container_name: idp-service
    volumes:
      - .:/app
    depends_on:
      - db-idp
      - redis-idp
    networks:
      - amaterasu-network

  db-idp:
    image: postgres:16
    container_name: idp-service-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: idp-service-pass
      POSTGRES_USER: idp-service-user
      POSTGRES_DB: idp-service-db
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    networks:
      - amaterasu-network

  redis-idp:
    image: "redis:7.0-alpine"
    container_name: idp-service-redis
    ports:
      - "6380:6379"
    networks:
      - amaterasu-network

  flyway-idp:
    image: flyway/flyway
    container_name: idp-service-migrate
    volumes:
      - ./migrations:/flyway/sql
    command: -url=jdbc:postgresql://db-idp:5432/idp-service-db -schemas=public -user=idp-service-user -password=idp-service-pass -connectRetries=60 migrate
    depends_on:
      - db-idp
    networks:
      - amaterasu-network

networks:
  amaterasu-network:
    name: amaterasu-network
    driver: bridge