spring:
  application:
    name: Brigid IdP

  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:idp-service-db}
    username: ${DB_USER:idp-service-user}
    password: ${DB_PASSWORD:idp-service-pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: ${DB_MIN_IDLE:5}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      connection-timeout: ${DB_CONN_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}

  jpa:
    properties:

      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:idp-service-db}
          autocommit: true
          username: ${DB_USER:idp-service-user}
          password: ${DB_PASSWORD:idp-service-pass}
          pool_size: ${DB_MAX_POOL_SIZE:20}

    hibernate:
      ddl-auto: validate

app:
  cache:
    db: ${REDIS_DB:0}
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

  apikey:
    idToken: ${API_KEY_ID_TOKEN:change-me}

  jwt:
    privateKey: ${JWT_RSA_PRIVATE_KEY:change-me}
    publicKey: ${JWT_RSA_PUBLIC_KEY:change-me}
    issuer: ${JWT_ISSUER:http://localhost:8080}