spring:
  application:
    name: Briged IdP

  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:idp-service-db}
    username: ${DB_USER:idp-service-user}
    password: ${DB_PASSWORD:idp-service-pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

app:
  cache:
    db: ${REDIS_DB:0}
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  apikey:
    idToken: ${API_KEY_ID_TOKEN:change-me}
  jwt:
    privateKey: ${JWT_RSA_PRIVATE_KEY:change-me}
    publicKey: ${JWT_RSA_PUBLIC_KEY:change-me}
    issuer: ${JWT_ISSUER:http://localhost:8080}